vm:
  name: debian           # VM name
  cpu: 2                 # CPU allocation in vCPUs
  memory: 2048           # Memory allocation in MB
  diskSize: 20           # Virtual disk size in GB
os:
  version: debian12      # Debian version
  diskImage: /var/lib/libvirt/images/debian-12.4.0-amd64-netinst.iso  # Path to disk image
  hostName: debian       # VM host name
  domainName: debian     # VM domain name
user:
  fullName: debian-user  # Debian user full name (does not have to be a real name)
  userName: debian-user  # Debian username
